on:
  push

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - run: choco install rust protoc
      - uses: actions/checkout@v4
      - run: |
          cargo build --release --target=x86_64-pc-windows-gnu
          # ref=$(echo '${{ github.ref }}' | sed -e s,refs/tags/,, )
          copy target/x86_64-pc-windows-gnu/release/velociraptor-client.exe velociraptor-client-x86_64-windows.exe
      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: windows-client
          path: velociraptor-client-*

  build_macosx:
    runs-on: macos-latest
    steps:
      - run: brew install rust protobuf
      - uses: actions/checkout@v4
      - run: |
          cargo build --release --target=x86_64-apple-darwin
          # ref=$(echo '${{ github.ref }}' | sed -e s,refs/tags/,, )
          ln target/x86_64-apple-darwin/release/velociraptor-client \
              velociraptor-client-x86_64-darwin
      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: macosx-client
          path: velociraptor-client-*
