on: [push, pull_request]

jobs:
  check_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: check formatting
        run: cargo fmt --check

  test:
    runs-on: ubuntu-latest
    container: alpine:3.18
    steps:
      - run: apk add bash curl build-base protobuf-dev
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: |
          cargo build
          cargo test
