on: [push, pull_request]

jobs:
  check_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: check formatting
        run: cargo fmt --check

  test:
    runs-on: ubuntu-latest
    container: alpine:3.18
    steps:
      - run: apk add build-base protobuf-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo build
          cargo test
